### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by Illutax** [caarlos0/uhr#5]
https://github.com/caarlos0/uhr/blob/2dc45a78d49538ae23daa095caaa262484970c3c/pkg/ui/model.go#L61

In this line you've used a dot for separating the hour from the minute, bit it should be a colon. Like so `12:34`.

**Comment by caarlos0** [comment]
It's not wrong, its fairly common to represent time like that in Germany, as far as I know.

**Comment by Illutax** [comment]
It's rather uncommon. There is only one correct format https://www.din-5008-richtlinien.de/startseite/uhrzeitangaben

**Comment by caarlos0** [comment]
ah, ok then, fixed!
thanks!

**Comment by Illutax** [comment]
You also might want to update the screenshot in the README.md :)
